### PR TITLE
Modeling Media Mix Models with SCMs

### PR DESCRIPTION
**Pull request by sameerkmarathe**
Project contains dataset, code and readme explaining the approach. Artefact project.

### CODE REVIEW

**Comment by robertness** [comment]
Looking good.

**Comment by vartikatewari** [comment]
Hi Sameer, 
Requested edits to the notebook. 
1. Theano version has conflicts with the pymc3 please add versions which you have used for installations. 
Screen Shot 2021-08-22 at 6 00 50 PM
2. Change the path of the dataset to make it compatible for running with your repo.

**Comment by sameerkmarathe** [comment]
made the changes from pull

**Comment by vartikatewari** [comment]
Hi @sameerkmarathe , The then , pymc error is fixed. But I'm getting an import error for mean_absolute_percentage_error
Screen Shot 2021-08-23 at 5 52 56 PM

**Comment by vartikatewari** [comment]
You can write your own function of the same name and that'll be the easiest fix.

**Comment by robertness** [comment]
> Hi @sameerkmarathe , The theano , pymc error is fixed. But I'm getting an import error for mean_absolute_percentage_error
> Screen Shot 2021-08-23 at 5 52 56 PM

Come on guys (@sameerkmarathe), this is rookie stuff.  Check your work and be respectful of the @vartikatewari's time.

**Comment by sameerkmarathe** [comment]
@robertness added the specific versions of the packages, this should work

**Comment by vartikatewari** [comment]
Hi @sameerkmarathe , Everything is running fine now . I'll go ahead and merge.

**Review by vartikatewari — APPROVED** [review]

**Pull request merged**
