### PR TITLE
Counterfactual Fairness in deep generative image models

### PR DESCRIPTION
**Pull request by VirenS13117**
@robertness
Final Project submission pull request for the project titled "Counterfactual Fairness in deep generative image models" for the course CS7290: Causal Machine Learning using PyTorch.
Contents : 
a. Article: A pdf file for the project description
b. src : causal_VAE_NF_generative_modelling.ipynb -> a runnable notebook in the medium style **article**
c. Images: Relevant images for the project.
***
**Student Names** : Sairah Joseph, Shubanshu Gupta, Neel Bhave, Virender Singh, Oj Sindher

### CODE REVIEW

**Comment by robertness** [comment]
Please create a README.md file.  See other projects from previous semesters for reference.  Also, include a link to a video describing the project.  Again see previous projects for reference.

**Comment by VirenS13117** [comment]
@robertness 
Thanks, updated with the README.md. Both readme and the main ipynb notebook contain project demonstration video link.
Also attaching here for your reference : [demo](https://www.youtube.com/watch?v=w5v-LX9ZIi0)

**Comment by vartikatewari** [comment]
Hi Virendra, Requested changes to the code. Add a shared link to the drive for data in the notebook. Right now it fails to run as the data isn't accessible.

**Comment by VirenS13117** [comment]
Hi @vartikatewari,
**drive data link** : https://drive.google.com/drive/folders/1B0239XvP15jG0jAuJT6oCSJERb5fGv_n?usp=sharing
As mentioned in the README.md. You will have to download data set from this link. https://storage.cloud.google.com/cartoonset_public_files/cartoonset10k.tgz
Make a folder **Causal_ML_Project** and put this zip file there. You can then run this code easily on google collab.
Since the code needs to run on gpu, that's why we are running this on collab and need to access data from the drive.
If you still face any difficulty running the code, we can set up a short call for the demo run.
Thanks

**Comment by vartikatewari** [comment]
Hi @VirenS13117 , Thanks for the drive link. You can instead use gdown to download data like this if you change permissions. 
Screen Shot 2021-08-22 at 6 55 42 PM
That will make it easier to reproduce.

**Comment by VirenS13117** [comment]
Thanks @vartikatewari,
I have made the necessary changes with the grown command. I have also added the google colab sharable link in the updated readme. You can access the code from there. 
Let me know if you are able to run it now. You can reach out to me on teams for any further clarification.

**Comment by vartikatewari** [comment]
Hi @VirenS13117 , I am able to run the code now. Merging the request.

**Review by vartikatewari — APPROVED** [review]

**Pull request merged**
