### PR TITLE
Causal Estimation of Wages

### PR DESCRIPTION
**Pull request by poojant99**

### CODE REVIEW

**Comment by prasadshreyas** [comment]
- [X] Run

Your notebook is zipped. Unzip and commit changes.

**Comment by poojant99** [comment]
Hi Shreyas,

The unzipped notebook is greater than the 25MB size limit for files, hence
I’ve zipped the notebook. Is there a workaround for this?

Best,
Poojan

**Comment by prasadshreyas** [comment]
Incorrect PR. Please create a separate directory for your notebook. Please look at other projects for references

**Comment by prasadshreyas** [comment]
- Looks good

**Pull request merged**
