### PR TITLE
Causal ML Wine Quality

### PR DESCRIPTION
**Pull request by RuchiB13**

### CODE REVIEW

**Comment by RuchiB13** [comment]
Causal ML for Wine Quality
By Andrew Lemke, Darshil Patel, Ruchi Bhavsar
For CS 7290 in Summer 2022 at Northeastern University

**Comment by prasadshreyas** [comment]
Make sure to commit all the necessary files. 

Missing: README.md

**Comment by prasadshreyas** [comment]
- [X] Run

Looks good.

**Comment by Cherez1** [comment]
Thanks for this RuchiB13

**Pull request merged**
